# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[[battery.display]] 
# "bold red" style and discharging_symbol when capacity is 
# between 0% and 10%
threshold = 10
style = "bold red"

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
